# Generated by Django 2.1.5 on 2019-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
